In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Ordinal Encoding

In [2]:
df = pd.read_csv("D://sampledata//campusx//customer.csv")

In [3]:
df.sample(10)

    age  gender   review education purchased
23   96  Female     Good    School        No
6    18    Male     Good    School        No
11   74    Male     Good        UG       Yes
45   61    Male     Poor        PG       Yes
0    30  Female  Average    School        No
8    65  Female  Average        UG        No
22   18  Female     Poor        PG       Yes
35   74    Male     Poor    School       Yes
34   86    Male  Average    School        No
20   57  Female  Average    School       Yes

In [4]:
df = df.iloc[:,2:]

In [13]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('purchased', axis=1),
                                                    df['purchased'],
                                                    test_size=0.2,
                                                    random_state=0)

X_train.shape, X_test.shape

((40, 2), (10, 2))

In [7]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [8]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [9]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [14]:
X_train

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [11]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoding

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:
le.fit(y_train)

LabelEncoder()

In [18]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [19]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [20]:
le.classes_

array(['No', 'Yes'], dtype=object)

# One-Hot Encoding

In [59]:
df = pd.read_csv("D://sampledata//campusx//cars.csv")

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [ ]:
df['brand'].value_counts()

In [24]:
df['brand'].nunique()

32

## 1> Using Pandas

In [25]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## 2> Using K-1 OneHot Encoding

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'], drop_first=True)

## 3> Using Sklearn

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [27]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [61]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],
                                                    df.iloc[:,-1],
                                                    test_size=0.2,
                                                    random_state=0)

In [62]:
ohe = OneHotEncoder() # can have parameters -> drop = 'first', sparse = True or False, dtype = np.32  
                      # in case of sparse = False, there is no need of use .toarray()
                      # in case of dtype = np.32, values will be converted to int instead of float

In [63]:
X_train_new =  ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [64]:
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()

In [33]:
X_train_new

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [34]:
X_train[['brand','km_driven']]

           brand  km_driven
3042     Hyundai      60000
1520        Tata     150000
2611     Hyundai     110000
3544    Mahindra      28000
4138      Maruti      15000
...          ...        ...
4931        Tata      70000
3264        Ford     100000
1653     Hyundai      90000
2607  Volkswagen      90000
2732     Hyundai     110000

[6502 rows x 2 columns]

In [35]:
X_train[['brand','km_driven']].values

array([['Hyundai', 60000],
       ['Tata', 150000],
       ['Hyundai', 110000],
       ...,
       ['Hyundai', 90000],
       ['Volkswagen', 90000],
       ['Hyundai', 110000]], dtype=object)

In [36]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new))

array([['Hyundai', 60000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 150000, 0.0, ..., 0.0, 0.0, 1.0],
       ['Hyundai', 110000, 0.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Hyundai', 90000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Volkswagen', 90000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 110000, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [37]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new)).shape

(6502, 11)

## One-Hot Encoding with top Categories

In [38]:
counts = df['brand'].value_counts()

In [39]:
df['brand'].nunique()
threshold = 100

In [40]:
repl = counts[counts <= threshold].index

In [41]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

# Column Transformer

In [42]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [43]:
df = pd.read_csv("D://sampledata//campusx//covid_toy.csv")

In [44]:
df.head(10)

   age  gender  fever   cough       city has_covid
0   60    Male  103.0    Mild    Kolkata        No
1   27    Male  100.0    Mild      Delhi       Yes
2   42    Male  101.0    Mild      Delhi        No
3   31  Female   98.0    Mild    Kolkata        No
4   65  Female  101.0    Mild     Mumbai        No
5   84  Female    NaN    Mild  Bangalore       Yes
6   14    Male  101.0  Strong  Bangalore        No
7   20  Female    NaN  Strong     Mumbai       Yes
8   19  Female  100.0  Strong  Bangalore        No
9   64  Female  101.0    Mild      Delhi        No

In [45]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:5], df.iloc[:,-1], test_size=0.2)

## Without column transformer

In [48]:
# adding simple imputer to fever column
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [49]:
# Ordinal encoder to cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.transform(X_test[['cough']])
X_train_cough.shape

(80, 1)

In [50]:
# One-Hot encoding to gender and city
ohe = OneHotEncoder(drop = 'first', sparse_output = False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.transform(X_test[['gender','city']])
X_train_gender_city.shape

(80, 4)

In [51]:
# Extracting age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age = X_train.drop(columns=['gender','fever','cough','city']).values
X_train_age.shape

(80, 1)

In [52]:
# Concatenating all this
X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)
X_test_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)
X_train_transformed.shape

(80, 7)

## With column transformer

In [53]:
from sklearn.compose import ColumnTransformer

In [54]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender','city'])
], remainder='passthrough') # remainder = passthrough or drop

In [55]:
transformer.fit_transform(X_train).shape

(80, 7)

In [56]:
transformer.transform(X_test).shape

(20, 7)