# Chi-Square Test
<pre> 
It is used to check if there is significant association between two categorical variables.
</pre>

### Chi-Square ($\chi^2$) Formula
The Chi-Square test measures how expectations compare to actual observed data.

$$\chi^2 = \sum \frac{(O_i - E_i)^2}{E_i}$$

**Where:**
* **$\chi^2$**: The Chi-Square statistic.
* **$\sum$**: The summation symbol (add up the results for all categories).
* **$O_i$**: The **Observed** frequency (the actual count you measured).
* **$E_i$**: The **Expected** frequency (the count predicted by the Null Hypothesis).
* **$i$**: The specific category or "cell" in your table.

### Expected Frequency ($E_{ij}$) Formula
In a contingency table, the expected frequency for a specific cell is calculated as:

$$E_{ij} = \frac{T_r \times T_c}{N}$$

**Where:**
* **$E_{ij}$**: The **Expected Frequency** for the cell in row *i* and column *j*.
* **$T_r$**: The **Row Total** (the sum of all observations in that specific row).
* **$T_c$**: The **Column Total** (the sum of all observations in that specific column).
* **$N$**: The **Grand Total** (the total number of all observations in the entire table).

Degree of Freedom: $ df = (r - 1)(c - 1)  $<br>
where r = number of rows, c = number of columns

In [2]:
import numpy as np 
import seaborn as sns
from scipy.stats import chi2_contingency
import pandas as pd

In [3]:
df = sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
contingency_table = pd.crosstab(df['sex'], df['survived'])
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [6]:
chi2, p_val, dof, expected = chi2_contingency(contingency_table)

In [7]:
expected

array([[193.47474747, 120.52525253],
       [355.52525253, 221.47474747]])

In [8]:
dof

1

In [9]:
p_val

1.1973570627755645e-58

In [10]:
chi2

260.71702016732104

In [11]:
alpha = 0.05
if p_val < alpha:
    print('Reject the null hypothesis, there is significant connection between gender and survival')
else:
    print("Accept the null hypothesis, there is no connection")

Reject the null hypothesis, there is significant connection between gender and survival